const currencies = [
  { code: "USD", name: "US Dollar", symbol: "$", exchangeRate: 1.0 },
  { code: "EUR", name: "Euro", symbol: "€", exchangeRate: 0.92 },
  { code: "GBP", name: "British Pound", symbol: "£", exchangeRate: 0.79 },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", exchangeRate: 148.5 },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", exchangeRate: 1.52 },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", exchangeRate: 1.36 },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", exchangeRate: 0.89 },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", exchangeRate: 7.24 },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", exchangeRate: 10.85 },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    symbol: "NZ$",
    exchangeRate: 1.64,
  },
  { code: "MXN", name: "Mexican Peso", symbol: "$", exchangeRate: 17.12 },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", exchangeRate: 1.34 },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", exchangeRate: 7.83 },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", exchangeRate: 10.92 },
  { code: "ZAR", name: "South African Rand", symbol: "R", exchangeRate: 18.45 },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", exchangeRate: 29.15 },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", exchangeRate: 5.18 },
  { code: "INR", name: "Indian Rupee", symbol: "₹", exchangeRate: 83.25 },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", exchangeRate: 92.5 },
  { code: "KRW", name: "South Korean Won", symbol: "₩", exchangeRate: 1305.0 },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", exchangeRate: 4.02 },
  { code: "THB", name: "Thai Baht", symbol: "฿", exchangeRate: 35.8 },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪", exchangeRate: 3.67 },
  { code: "DKK", name: "Danish Krone", symbol: "kr", exchangeRate: 6.86 },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", exchangeRate: 355.0 },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", exchangeRate: 22.65 },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", exchangeRate: 3.67 },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", exchangeRate: 3.75 },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", exchangeRate: 9.85 },
  { code: "RON", name: "Romanian Leu", symbol: "lei", exchangeRate: 4.58 },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", exchangeRate: 1.8 },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", exchangeRate: 6.93 },
  { code: "ISK", name: "Icelandic Krona", symbol: "kr", exchangeRate: 137.5 },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", exchangeRate: 56.2 },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", exchangeRate: 4.68 },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    exchangeRate: 15650.0,
  },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", exchangeRate: 24350.0 },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", exchangeRate: 30.85 },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼", exchangeRate: 3.64 },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", exchangeRate: 0.31 },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", exchangeRate: 0.38 },
  { code: "OMR", name: "Omani Rial", symbol: "﷼", exchangeRate: 0.38 },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", exchangeRate: 0.71 },
  { code: "LBP", name: "Lebanese Pound", symbol: "£", exchangeRate: 89500.0 },
  { code: "CLP", name: "Chilean Peso", symbol: "$", exchangeRate: 890.0 },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", exchangeRate: 3.78 },
  { code: "COP", name: "Colombian Peso", symbol: "$", exchangeRate: 4125.0 },
  { code: "ARS", name: "Argentine Peso", symbol: "$", exchangeRate: 850.0 },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", exchangeRate: 39.25 },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$", exchangeRate: 31.45 },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨", exchangeRate: 325.0 },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", exchangeRate: 278.5 },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", exchangeRate: 109.5 },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", exchangeRate: 133.2 },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", exchangeRate: 70.15 },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", exchangeRate: 42000.0 },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", exchangeRate: 1310.0 },
  { code: "SYP", name: "Syrian Pound", symbol: "£", exchangeRate: 2512.0 },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", exchangeRate: 2.68 },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", exchangeRate: 387.5 },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", exchangeRate: 1.7 },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", exchangeRate: 3.28 },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", exchangeRate: 37.15 },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", exchangeRate: 17.85 },
  { code: "RSD", name: "Serbian Dinar", symbol: "Дин.", exchangeRate: 107.8 },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", exchangeRate: 56.75 },
  { code: "ALL", name: "Albanian Lek", symbol: "L", exchangeRate: 92.5 },
  {
    code: "BAM",
    name: "Bosnia-Herzegovina Convertible Mark",
    symbol: "KM",
    exchangeRate: 1.8,
  },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", exchangeRate: 775.0 },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "¢", exchangeRate: 12.15 },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", exchangeRate: 129.5 },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    symbol: "USh",
    exchangeRate: 3785.0,
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    symbol: "TSh",
    exchangeRate: 2350.0,
  },
  { code: "RWF", name: "Rwandan Franc", symbol: "RF", exchangeRate: 1285.0 },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", exchangeRate: 56.25 },
  {
    code: "XOF",
    name: "West African CFA Franc",
    symbol: "CFA",
    exchangeRate: 603.5,
  },
  {
    code: "XAF",
    name: "Central African CFA Franc",
    symbol: "FCFA",
    exchangeRate: 603.5,
  },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", exchangeRate: 134.2 },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", exchangeRate: 3.12 },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", exchangeRate: 4.82 },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", exchangeRate: 602.0 },
  {
    code: "MZN",
    name: "Mozambican Metical",
    symbol: "MT",
    exchangeRate: 63.85,
  },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", exchangeRate: 825.0 },
  { code: "BWP", name: "Botswanan Pula", symbol: "P", exchangeRate: 13.65 },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "L", exchangeRate: 18.45 },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", exchangeRate: 18.45 },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$", exchangeRate: 18.45 },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", exchangeRate: 1685.0 },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", exchangeRate: 25.8 },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$", exchangeRate: 322.0 },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", exchangeRate: 45.35 },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", exchangeRate: 13.25 },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", exchangeRate: 4515.0 },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", exchangeRate: 452.5 },
  {
    code: "CVE",
    name: "Cape Verdean Escudo",
    symbol: "$",
    exchangeRate: 101.5,
  },
  {
    code: "STN",
    name: "São Tomé and Príncipe Dobra",
    symbol: "Db",
    exchangeRate: 22.5,
  },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", exchangeRate: 67.25 },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", exchangeRate: 8600.0 },
  {
    code: "SLL",
    name: "Sierra Leonean Leone",
    symbol: "Le",
    exchangeRate: 20700.0,
  },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", exchangeRate: 185.5 },
  { code: "CDF", name: "Congolese Franc", symbol: "FC", exchangeRate: 2785.0 },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", exchangeRate: 2875.0 },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", exchangeRate: 177.7 },
  { code: "SOS", name: "Somali Shilling", symbol: "S", exchangeRate: 570.0 },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", exchangeRate: 15.0 },
];
currencies.sort((a, b) => a.code.localeCompare(b.code));
export default currencies;
