 const currencies = [
    { code: "USD", name: "US Dollar", symbol: "$" },
    { code: "EUR", name: "Euro", symbol: "€" },
    { code: "GBP", name: "British Pound", symbol: "£" },
    { code: "JPY", name: "Japanese Yen", symbol: "¥" },
    { code: "AUD", name: "Australian Dollar", symbol: "A$" },
    { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
    { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
    { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
    { code: "MXN", name: "Mexican Peso", symbol: "$" },
    { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
    { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
    { code: "ZAR", name: "South African Rand", symbol: "R" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$" },
    { code: "INR", name: "Indian Rupee", symbol: "₹" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽" },
    { code: "KRW", name: "South Korean Won", symbol: "₩" },
    { code: "PLN", name: "Polish Zloty", symbol: "zł" },
    { code: "THB", name: "Thai Baht", symbol: "฿" },
    { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
    { code: "DKK", name: "Danish Krone", symbol: "kr" },
    { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
    { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
    { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
    { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
    { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
    { code: "RON", name: "Romanian Leu", symbol: "lei" },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
    { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
    { code: "ISK", name: "Icelandic Krona", symbol: "kr" },
    { code: "PHP", name: "Philippine Peso", symbol: "₱" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
    { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
    { code: "EGP", name: "Egyptian Pound", symbol: "£" },
    { code: "QAR", name: "Qatari Riyal", symbol: "﷼" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
    { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب" },
    { code: "OMR", name: "Omani Rial", symbol: "﷼" },
    { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا" },
    { code: "LBP", name: "Lebanese Pound", symbol: "£" },
    { code: "CLP", name: "Chilean Peso", symbol: "$" },
    { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
    { code: "COP", name: "Colombian Peso", symbol: "$" },
    { code: "ARS", name: "Argentine Peso", symbol: "$" },
    { code: "UYU", name: "Uruguayan Peso", symbol: "$U" },
    { code: "TWD", name: "Taiwan Dollar", symbol: "NT$" },
    { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨" },
    { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
    { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
    { code: "NPR", name: "Nepalese Rupee", symbol: "₨" },
    { code: "AFN", name: "Afghan Afghani", symbol: "؋" },
    { code: "IRR", name: "Iranian Rial", symbol: "﷼" },
    { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د" },
    { code: "SYP", name: "Syrian Pound", symbol: "£" },
    { code: "GEL", name: "Georgian Lari", symbol: "₾" },
    { code: "AMD", name: "Armenian Dram", symbol: "֏" },
    { code: "AZN", name: "Azerbaijani Manat", symbol: "₼" },
    { code: "BYN", name: "Belarusian Ruble", symbol: "Br" },
    { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
    { code: "MDL", name: "Moldovan Leu", symbol: "L" },
    { code: "RSD", name: "Serbian Dinar", symbol: "Дин." },
    { code: "MKD", name: "Macedonian Denar", symbol: "ден" },
    { code: "ALL", name: "Albanian Lek", symbol: "L" },
    { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
    { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
    { code: "GHS", name: "Ghanaian Cedi", symbol: "¢" },
    { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
    { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
    { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
    { code: "RWF", name: "Rwandan Franc", symbol: "RF" },
    { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
    { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
    { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
    { code: "DZD", name: "Algerian Dinar", symbol: "د.ج" },
    { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
    { code: "LYD", name: "Libyan Dinar", symbol: "ل.د" },
    { code: "SDG", name: "Sudanese Pound", symbol: "ج.س." },
    { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
    { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
    { code: "BWP", name: "Botswanan Pula", symbol: "P" },
    { code: "SZL", name: "Swazi Lilangeni", symbol: "L" },
    { code: "LSL", name: "Lesotho Loti", symbol: "L" },
    { code: "NAD", name: "Namibian Dollar", symbol: "N$" },
    { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
    { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
    { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$" },
    { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
    { code: "SCR", name: "Seychellois Rupee", symbol: "₨" },
    { code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
    { code: "KMF", name: "Comorian Franc", symbol: "CF" },
    { code: "CVE", name: "Cape Verdean Escudo", symbol: "$" },
    { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db" },
    { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
    { code: "GNF", name: "Guinean Franc", symbol: "FG" },
    { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le" },
    { code: "LRD", name: "Liberian Dollar", symbol: "L$" },
    { code: "CDF", name: "Congolese Franc", symbol: "FC" },
    { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
    { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
    { code: "SOS", name: "Somali Shilling", symbol: "S" },
    { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk" },
  ];
  currencies.sort((a, b) => a.code.localeCompare(b.code));
  export default currencies;